// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/guide":{"path":"guide","id":"docs/guide","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"components/button/index":{"id":"components/button/index","path":"components/button","parentId":"DocLayout","meta":{"_atom_route":true}},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/JoeWright/workspace/mobile-kit/node_modules/.pnpm/dumi@2.4.23_@babel+core@7.29.0_@swc+helpers@0.5.15_@types+node@25.5.0_@types+react@18.3_23089b9682618f24422562e44a06a82c/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/JoeWright/workspace/mobile-kit/.dumi/tmp/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/JoeWright/workspace/mobile-kit/node_modules/.pnpm/dumi@2.4.23_@babel+core@7.29.0_@swc+helpers@0.5.15_@types+node@25.5.0_@types+react@18.3_23089b9682618f24422562e44a06a82c/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/guide': React.lazy(() => import(/* webpackChunkName: "docs__guide.md" */'/Users/JoeWright/workspace/mobile-kit/docs/guide.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/JoeWright/workspace/mobile-kit/docs/index.md')),
'components/button/index': React.lazy(() => import(/* webpackChunkName: "components__button__index.md" */'/Users/JoeWright/workspace/mobile-kit/src/components/button/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/JoeWright/workspace/mobile-kit/node_modules/.pnpm/dumi@2.4.23_@babel+core@7.29.0_@swc+helpers@0.5.15_@types+node@25.5.0_@types+react@18.3_23089b9682618f24422562e44a06a82c/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
