// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from '/Users/JoeWright/workspace/mobile-kit/docs/guide.md?type=frontmatter';
import { demoIndex as dmi0 } from '/Users/JoeWright/workspace/mobile-kit/docs/guide.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from '/Users/JoeWright/workspace/mobile-kit/docs/index.md?type=frontmatter';
import { demoIndex as dmi1 } from '/Users/JoeWright/workspace/mobile-kit/docs/index.md?type=demo-index';
import { frontmatter as fm2, toc as t2 } from '/Users/JoeWright/workspace/mobile-kit/src/components/button/index.md?type=frontmatter';
import { demoIndex as dmi2 } from '/Users/JoeWright/workspace/mobile-kit/src/components/button/index.md?type=demo-index';
import { frontmatter as fm3, toc as t3 } from '/Users/JoeWright/workspace/mobile-kit/src/components/popup/index.md?type=frontmatter';
import { demoIndex as dmi3 } from '/Users/JoeWright/workspace/mobile-kit/src/components/popup/index.md?type=demo-index';

export const filesMeta = {
  'docs/guide': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/JoeWright/workspace/mobile-kit/docs/guide.md?type=text'),
  },
  'docs/index': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/JoeWright/workspace/mobile-kit/docs/index.md?type=text'),
  },
  'components/button/index': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/JoeWright/workspace/mobile-kit/src/components/button/index.md?type=text'),
  },
  'components/popup/index': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/JoeWright/workspace/mobile-kit/src/components/popup/index.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
