// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/JoeWright/workspace/mobile-kit/node_modules/.pnpm/dumi@2.4.23_@babel+core@7.29.0_@swc+helpers@0.5.15_@types+node@25.5.0_@types+react@18.3_23089b9682618f24422562e44a06a82c/node_modules/dumi/theme-default/slots/NotFound/index.js';
